name: Dependabot Auto Merge

on: [push, pull_request]

jobs:
    build-and-test:
        name: Run tests
        runs-on: ubuntu-latest
        steps:
            - name: Git checkout
              uses: actions/checkout@v2

            - name: Install dependencies, build, then test
              run: |
                npm install
                npm run build
                npm run test

    automerge:
        needs: build-and-test
        runs-on: ubuntu-latest
        steps:
            - uses: fastify/github-action-merge-dependabot@v1
              if: ${{ github.actor == 'dependabot[bot]' && github.event_name == 'pull_request' }}
              with:
                  github-token: ${{secrets.github_token}}
                  merge-method: 'squash'
